import { GetStaticProps } from 'next'
import Head from 'next/head'
import fs from 'fs'
import matter from 'gray-matter'
import Link from 'next/link'
import { Matter, Post } from '../types/post'
import PostItemCard from '../components/post-item-card'

export const getStaticProps: GetStaticProps<{ posts: Post[] }> = () => {
  const files = fs.readdirSync('posts')
  const posts = files.map((fileName) => {
    const slug = fileName.replace(/\.md$/, '')
    const fileContent = fs.readFileSync(`posts/${fileName}`, 'utf-8')
    const { data, content } = matter(fileContent)
    return {
      matter: data as Matter,
      slug,
      content,
    }
  })
  return {
    props: {
      posts,
    },
  }
}

export default function Home({ posts }: { posts: Post[] }) {
  return (
    <>
      <Head>
        <title>TOPページ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid grid-cols-3">
          {posts.map((post) => (
            <PostItemCard key={post.slug} post={post} />
          ))}
        </div>
      </main>
    </>
  )
}
